/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quotes
         * @description Fan out to adapters and return SizeQuotePair rows for one asset/notional.
         */
        get: operations["get_quotes_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Venues
         * @description Static venue registry + whether an adapter is currently registered.
         */
        get: operations["get_venues_venues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assets
         * @description Logical assets + per-venue representation labels (WHI-798 §3.3).
         */
        get: operations["get_assets_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fees
         * @description All validated venue fee schedules (WHI-812; frontend contract for WHI-813).
         */
        get: operations["get_fees_fees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetResponse
         * @description One row of ``GET /assets``.
         */
        AssetResponse: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /**
             * Representations
             * @description Venue slug → representation label (WHI-798 §3.3).
             */
            representations: {
                [key: string]: string;
            };
        };
        /**
         * FeeBreakdown
         * @description Per-quote fee components (WHI-799 §5.4). bps fields are authoritative.
         */
        FeeBreakdown: {
            /** Embedded In Price */
            embedded_in_price: boolean;
            /** Fee Tier */
            fee_tier?: string | null;
            /** Trading Fee Bps */
            trading_fee_bps?: string | null;
            /** Trading Fee Usd */
            trading_fee_usd?: string | null;
            /**
             * Platform Fee Bps
             * @default 0
             */
            platform_fee_bps: string;
            /** Lp Fee Tier Bps */
            lp_fee_tier_bps?: string | null;
            /** Gas Usd */
            gas_usd?: string | null;
            /** Gas Bps */
            gas_bps?: string | null;
            /**
             * Gas Unknown
             * @default false
             */
            gas_unknown: boolean;
            /** Funding Rate 8H */
            funding_rate_8h?: string | null;
            /** Explicit Fee Bps */
            explicit_fee_bps?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * FeeSchedule
         * @description Venue-level fee table shape (WHI-799 §5.5). Numbers filled by WHI-812.
         */
        FeeSchedule: {
            /** Venue */
            venue: string;
            /** Asset */
            asset?: string | null;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /** Maker Bps */
            maker_bps?: string | null;
            /** Taker Bps */
            taker_bps?: string | null;
            /** Tiers */
            tiers?: components["schemas"]["FeeTier"][] | null;
            /**
             * Default Tier
             * @default default_taker
             */
            default_tier: string;
            /** Lp Fee Tiers Bps */
            lp_fee_tiers_bps?: string[] | null;
            /** Gas Estimate Usd */
            gas_estimate_usd?: string | null;
            /**
             * Funding Model
             * @default none
             * @enum {string}
             */
            funding_model: "none" | "perp_8h" | "perp_continuous";
            /**
             * Fee Embedded In Quote
             * @default false
             */
            fee_embedded_in_quote: boolean;
            /** Source Urls */
            source_urls?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FeeTier
         * @description One fee tier inside a FeeSchedule (WHI-799 §5.5).
         */
        FeeTier: {
            /** Name */
            name: string;
            /** Maker Bps */
            maker_bps: string;
            /** Taker Bps */
            taker_bps: string;
            /** Volume Requirement */
            volume_requirement?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload for ``GET /health``.
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' when the process is serving.
             */
            status: string;
            /**
             * Adapters Initialized
             * @description Adapters whose startup() completed successfully.
             */
            adapters_initialized: number;
        };
        /**
         * Quote
         * @description Single venue quote at a notional size (WHI-799 §6.2).
         */
        Quote: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /** Venue Symbol */
            venue_symbol?: string | null;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Notional Usd */
            notional_usd: string;
            /** Mid */
            mid: string;
            /**
             * Mid Source
             * @enum {string}
             */
            mid_source: "binance_usdm_index" | "binance_spot_tob" | "bybit_spot_tob" | "pyth" | "cex_tradfi_index" | "proxy_perp_mark_median" | "equity_ref_same_as_perp";
            /**
             * Mid Timestamp
             * Format: date-time
             */
            mid_timestamp: string;
            /**
             * Mid Stale
             * @default false
             */
            mid_stale: boolean;
            /** Effective Price */
            effective_price?: string | null;
            /** Spread Bps */
            spread_bps?: string | null;
            fee_breakdown: components["schemas"]["FeeBreakdown"];
            /** Total Cost Bps */
            total_cost_bps?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_quote" | "insufficient_liquidity" | "unsupported_asset" | "error";
            /** Qty Base */
            qty_base?: string | null;
            /** Qty Method */
            qty_method?: ("base_from_mid" | "quote_exact_in_approx") | null;
            /** Venue Mark */
            venue_mark?: string | null;
            /** Basis Bps */
            basis_bps?: string | null;
            /** Raw Ref */
            raw_ref?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * QuotesResponse
         * @description ``GET /quotes`` payload.
         */
        QuotesResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Asset */
            asset: string;
            /** Notional Usd */
            notional_usd: string;
            mid: components["schemas"]["ReferenceMid"];
            /** Pairs */
            pairs: components["schemas"]["SizeQuotePair"][];
        };
        /**
         * ReferenceMid
         * @description Snapshot-scoped reference mid shared by all venues (WHI-799 §3.5).
         */
        ReferenceMid: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Asset */
            asset: string;
            /** Mid */
            mid: string;
            /**
             * Mid Source
             * @enum {string}
             */
            mid_source: "binance_usdm_index" | "binance_spot_tob" | "bybit_spot_tob" | "pyth" | "cex_tradfi_index" | "proxy_perp_mark_median" | "equity_ref_same_as_perp";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Sources Detail */
            sources_detail?: string[] | null;
        };
        /**
         * SizeQuotePair
         * @description Buy+sell pair at one size for one venue (WHI-799 §6.4; aggregator synthesizes).
         */
        SizeQuotePair: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /** Notional Usd */
            notional_usd: string;
            buy?: components["schemas"]["Quote"] | null;
            sell?: components["schemas"]["Quote"] | null;
            /** Round Trip Spread Bps */
            round_trip_spread_bps?: string | null;
            /** Half Spread Bps */
            half_spread_bps?: string | null;
            /** Round Trip Total Cost Bps */
            round_trip_total_cost_bps?: string | null;
            top_of_book?: components["schemas"]["TopOfBook"] | null;
        };
        /**
         * TopOfBook
         * @description Orderbook top-of-book snapshot (WHI-799 §6.3). AMM/Prop never produce this.
         */
        TopOfBook: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp";
            /** Best Bid */
            best_bid: string;
            /** Best Ask */
            best_ask: string;
            /** Bid Size */
            bid_size?: string | null;
            /** Ask Size */
            ask_size?: string | null;
            /** Mid Local */
            mid_local: string;
            /** Mid Ref */
            mid_ref: string;
            /**
             * Mid Timestamp
             * Format: date-time
             */
            mid_timestamp: string;
            /** Spread Bps */
            spread_bps: string;
            /** Spread Bps Local */
            spread_bps_local: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VenueResponse
         * @description One row of ``GET /venues``.
         */
        VenueResponse: {
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /**
             * Venue Class
             * @enum {string}
             */
            venue_class: "cex" | "perp_dex" | "amm_dex" | "prop_amm";
            /** Chain */
            chain?: string | null;
            /**
             * Adapter Registered
             * @default false
             */
            adapter_registered: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_quotes_quotes_get: {
        parameters: {
            query: {
                /** @description Logical asset id, e.g. BTC */
                asset: string;
                /** @description USD notional; one of 1000 / 10000 / 100000 / 1000000 (WHI-799 §4.1) */
                notional: string;
                /** @description Comma-separated venue slugs; default = all registered adapters */
                venues?: string | null;
                /** @description If set, only that leg is fetched */
                side?: ("buy" | "sell") | null;
                /** @description Override adapter default instrument type */
                instrument_type?: ("spot" | "perp" | "amm_pool" | "prop_amm") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_venues_venues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueResponse"][];
                };
            };
        };
    };
    get_assets_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"][];
                };
            };
        };
    };
    get_fees_fees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeSchedule"][];
                };
            };
        };
    };
}
