/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quotes
         * @description Fan out to adapters; one asset, one or many notional tiers (WHI-843).
         */
        get: operations["get_quotes_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Venues
         * @description Static venue registry + whether an adapter is currently registered.
         *
         *     Venues disabled in ``config/venues.yaml`` are omitted entirely (WHI-840) so
         *     they do not appear as quote targets and consume no fan-out budget.
         */
        get: operations["get_venues_venues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assets
         * @description Logical assets + per-venue representation labels (WHI-798 §3.3).
         */
        get: operations["get_assets_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fees
         * @description All validated venue fee schedules (WHI-812; frontend contract for WHI-813).
         */
        get: operations["get_fees_fees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List valid simulate pair legs
         * @description Return tradeable stables and catalogued assets for pair construction.
         *
         *     Discovery only — does not change ``POST /simulate`` validation. Clients
         *     should not hardcode USDC/USDT; this list is the SSOT (WHI-833).
         */
        get: operations["get_simulate_pairs_simulate_pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Simulate
         * @description Fan out a free-form pair trade to adapters; rank by expected output.
         */
        post: operations["post_simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetResponse
         * @description One row of ``GET /assets``.
         */
        AssetResponse: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /**
             * Representations
             * @description Venue slug → representation label (WHI-798 §3.3).
             */
            representations: {
                [key: string]: string;
            };
        };
        /**
         * FeeBreakdown
         * @description Per-quote fee components (WHI-799 §5.4). bps fields are authoritative.
         */
        FeeBreakdown: {
            /** Embedded In Price */
            embedded_in_price: boolean;
            /** Fee Tier */
            fee_tier?: string | null;
            /** Trading Fee Bps */
            trading_fee_bps?: string | null;
            /** Trading Fee Usd */
            trading_fee_usd?: string | null;
            /**
             * Platform Fee Bps
             * @default 0
             */
            platform_fee_bps: string;
            /** Lp Fee Tier Bps */
            lp_fee_tier_bps?: string | null;
            /** Gas Usd */
            gas_usd?: string | null;
            /** Gas Bps */
            gas_bps?: string | null;
            /**
             * Gas Unknown
             * @default false
             */
            gas_unknown: boolean;
            /** Funding Rate 8H */
            funding_rate_8h?: string | null;
            /** Explicit Fee Bps */
            explicit_fee_bps?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * FeeSchedule
         * @description Venue-level fee table shape (WHI-799 §5.5). Numbers filled by WHI-812.
         */
        FeeSchedule: {
            /** Venue */
            venue: string;
            /** Asset */
            asset?: string | null;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /** Maker Bps */
            maker_bps?: string | null;
            /** Taker Bps */
            taker_bps?: string | null;
            /** Tiers */
            tiers?: components["schemas"]["FeeTier"][] | null;
            /**
             * Default Tier
             * @default default_taker
             */
            default_tier: string;
            /** Lp Fee Tiers Bps */
            lp_fee_tiers_bps?: string[] | null;
            /** Gas Estimate Usd */
            gas_estimate_usd?: string | null;
            /**
             * Funding Model
             * @default none
             * @enum {string}
             */
            funding_model: "none" | "perp_8h" | "perp_continuous";
            /**
             * Fee Embedded In Quote
             * @default false
             */
            fee_embedded_in_quote: boolean;
            /** Source Urls */
            source_urls?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FeeTier
         * @description One fee tier inside a FeeSchedule (WHI-799 §5.5).
         */
        FeeTier: {
            /** Name */
            name: string;
            /** Maker Bps */
            maker_bps: string;
            /** Taker Bps */
            taker_bps: string;
            /** Volume Requirement */
            volume_requirement?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload for ``GET /health`` (WHI-840: degradation without flap).
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' when the process is serving.
             */
            status: string;
            /**
             * Adapters Initialized
             * @description Adapters whose startup() completed successfully.
             */
            adapters_initialized: number;
            /**
             * Adapters Expected
             * @description Enabled adapters that should be started (excludes config-disabled).
             */
            adapters_expected: number;
            /**
             * Degraded
             * @description True when at least one enabled adapter is not initialized.
             */
            degraded: boolean;
            /**
             * Unavailable Venues
             * @description Enabled venue slugs that failed or have not completed startup.
             */
            unavailable_venues: string[];
        };
        /**
         * Quote
         * @description Single venue quote at a notional size (WHI-799 §6.2).
         */
        Quote: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /** Venue Symbol */
            venue_symbol?: string | null;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Notional Usd */
            notional_usd: string;
            /** Mid */
            mid: string;
            /**
             * Mid Source
             * @enum {string}
             */
            mid_source: "binance_usdm_index" | "binance_spot_tob" | "bybit_spot_tob" | "pyth" | "cex_tradfi_index" | "proxy_perp_mark_median" | "equity_ref_same_as_perp";
            /**
             * Mid Timestamp
             * Format: date-time
             */
            mid_timestamp: string;
            /**
             * Mid Stale
             * @default false
             */
            mid_stale: boolean;
            /**
             * Quote Stale
             * @default false
             */
            quote_stale: boolean;
            /** Age Sec */
            age_sec?: number | null;
            /** Effective Price */
            effective_price?: string | null;
            /** Spread Bps */
            spread_bps?: string | null;
            fee_breakdown: components["schemas"]["FeeBreakdown"];
            /** Total Cost Bps */
            total_cost_bps?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_quote" | "insufficient_liquidity" | "unsupported_asset" | "error" | "rate_limited" | "excessive_impact";
            /** Qty Base */
            qty_base?: string | null;
            /** Qty Method */
            qty_method?: ("base_from_mid" | "quote_exact_in_approx") | null;
            /** Venue Mark */
            venue_mark?: string | null;
            /** Basis Bps */
            basis_bps?: string | null;
            /** Raw Ref */
            raw_ref?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Price Impact Bps */
            price_impact_bps?: string | null;
        };
        /**
         * QuotesResponse
         * @description ``GET /quotes`` payload.
         *
         *     Single-tier calls set ``notional_usd`` to that tier and ``notionals`` to a
         *     one-element list. Multi-tier calls (``?notionals=…``) return every tier's
         *     pairs under one ``snapshot_id`` / mid; ``notional_usd`` is the first
         *     (sorted) tier for back-compat (WHI-843).
         */
        QuotesResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Asset */
            asset: string;
            /** Notional Usd */
            notional_usd: string;
            mid: components["schemas"]["ReferenceMid"];
            /** Pairs */
            pairs: components["schemas"]["SizeQuotePair"][];
            /**
             * Notionals
             * @description Requested notional tiers (USD); always non-empty.
             */
            notionals: string[];
        };
        /**
         * ReferenceMid
         * @description Snapshot-scoped reference mid shared by all venues (WHI-799 §3.5).
         */
        ReferenceMid: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Asset */
            asset: string;
            /** Mid */
            mid: string;
            /**
             * Mid Source
             * @enum {string}
             */
            mid_source: "binance_usdm_index" | "binance_spot_tob" | "bybit_spot_tob" | "pyth" | "cex_tradfi_index" | "proxy_perp_mark_median" | "equity_ref_same_as_perp";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Sources Detail */
            sources_detail?: string[] | null;
        };
        /**
         * SimulatePairErrorDetail
         * @description Structured 422 body for pair validation failures (WHI-814 / WHI-815 client).
         */
        SimulatePairErrorDetail: {
            /** Message */
            message: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "unknown_asset" | "cross_pair";
        };
        /**
         * SimulatePairsResponse
         * @description ``GET /simulate/pairs`` — valid legs for building a simulate pair (WHI-833).
         *
         *     Contract for WHI-815: clients form pairs as (one of ``stables``) ×
         *     (one of ``assets``), either direction. Exactly one leg must be a tradeable
         *     stable; ``USD`` is never listed (peg-only, not tradeable).
         */
        SimulatePairsResponse: {
            /**
             * Stables
             * @description Tradeable USD stablecoin symbols accepted as a pair leg (no USD).
             */
            stables: string[];
            /**
             * Assets
             * @description Catalogued non-stable logical assets for the other leg.
             */
            assets: string[];
        };
        /**
         * SimulateRequest
         * @description ``POST /simulate`` body: sell/buy assets and amount in sell-asset units.
         */
        SimulateRequest: {
            /**
             * Sell Asset
             * @description Asset the user sells, e.g. SOL or USDC
             */
            sell_asset: string;
            /**
             * Buy Asset
             * @description Asset the user receives, e.g. USDC or SOL
             */
            buy_asset: string;
            /**
             * Amount
             * @description Quantity of sell_asset (free-form; not snapped to notional tiers)
             */
            amount: number | string;
            /**
             * Venues
             * @description Optional venue slug filter; default = all registered adapters
             */
            venues?: string[] | null;
            /**
             * Instrument Type
             * @description Override adapter default instrument type when the class supports it
             */
            instrument_type?: ("spot" | "perp" | "amm_pool" | "prop_amm") | null;
        };
        /**
         * SimulateResponse
         * @description ``POST /simulate`` payload — contract for WHI-815.
         */
        SimulateResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Sell Asset */
            sell_asset: string;
            /** Buy Asset */
            buy_asset: string;
            /** Amount */
            amount: string;
            /**
             * Asset
             * @description Non-stable leg passed to adapters
             */
            asset: string;
            /**
             * Side
             * @description Adapter side: sell when selling non-stable, buy otherwise
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Notional Usd */
            notional_usd: string;
            mid: components["schemas"]["ReferenceMid"];
            /** Rows */
            rows: components["schemas"]["SimulateRowResponse"][];
        };
        /**
         * SimulateRowResponse
         * @description One ranked venue row in the simulate response.
         */
        SimulateRowResponse: {
            /** Venue */
            venue: string;
            /** Venue Symbol */
            venue_symbol?: string | null;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /** Expected Output */
            expected_output?: string | null;
            /** Effective Price */
            effective_price?: string | null;
            /** Spread Bps */
            spread_bps?: string | null;
            fee_breakdown: components["schemas"]["FeeBreakdown"];
            /** Total Cost Bps */
            total_cost_bps?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Status */
            status: ("ok" | "no_quote" | "insufficient_liquidity" | "unsupported_asset" | "error" | "rate_limited" | "excessive_impact") | "not_supported";
            /**
             * Best
             * @default false
             */
            best: boolean;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Mid Stale
             * @default false
             */
            mid_stale: boolean;
            /**
             * Quote Stale
             * @default false
             */
            quote_stale: boolean;
        };
        /**
         * SizeQuotePair
         * @description Buy+sell pair at one size for one venue (WHI-799 §6.4; aggregator synthesizes).
         */
        SizeQuotePair: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp" | "amm_pool" | "prop_amm";
            /** Notional Usd */
            notional_usd: string;
            buy?: components["schemas"]["Quote"] | null;
            sell?: components["schemas"]["Quote"] | null;
            /** Round Trip Spread Bps */
            round_trip_spread_bps?: string | null;
            /** Half Spread Bps */
            half_spread_bps?: string | null;
            /** Round Trip Total Cost Bps */
            round_trip_total_cost_bps?: string | null;
            top_of_book?: components["schemas"]["TopOfBook"] | null;
        };
        /**
         * TopOfBook
         * @description Orderbook top-of-book snapshot (WHI-799 §6.3). AMM/Prop never produce this.
         */
        TopOfBook: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Venue */
            venue: string;
            /** Asset */
            asset: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spot" | "perp";
            /** Best Bid */
            best_bid: string;
            /** Best Ask */
            best_ask: string;
            /** Bid Size */
            bid_size?: string | null;
            /** Ask Size */
            ask_size?: string | null;
            /** Mid Local */
            mid_local: string;
            /** Mid Ref */
            mid_ref: string;
            /**
             * Mid Timestamp
             * Format: date-time
             */
            mid_timestamp: string;
            /** Spread Bps */
            spread_bps: string;
            /** Spread Bps Local */
            spread_bps_local: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VenueResponse
         * @description One row of ``GET /venues``.
         */
        VenueResponse: {
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /**
             * Venue Class
             * @enum {string}
             */
            venue_class: "cex" | "perp_dex" | "amm_dex" | "prop_amm";
            /** Chain */
            chain?: string | null;
            /**
             * Adapter Registered
             * @default false
             */
            adapter_registered: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_quotes_quotes_get: {
        parameters: {
            query: {
                /** @description Logical asset id, e.g. BTC */
                asset: string;
                /** @description Single USD notional; one of 100 / 1000 / 10000 / 100000 / 1000000 (WHI-799 §4.1). Mutually exclusive with ``notionals``. */
                notional?: string | null;
                /** @description Comma-separated USD notionals (multi-tier package, WHI-843); each must be a §4.1 tier. Mutually exclusive with ``notional``. */
                notionals?: string | null;
                /** @description Comma-separated venue slugs; default = all registered adapters */
                venues?: string | null;
                /** @description If set, only that leg is fetched */
                side?: ("buy" | "sell") | null;
                /** @description Override adapter default instrument type */
                instrument_type?: ("spot" | "perp" | "amm_pool" | "prop_amm") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_venues_venues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueResponse"][];
                };
            };
        };
    };
    get_assets_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"][];
                };
            };
        };
    };
    get_fees_fees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeSchedule"][];
                };
            };
        };
    };
    get_simulate_pairs_simulate_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatePairsResponse"];
                };
            };
        };
    };
    post_simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Pair validation or request body error. Pair failures use SimulatePairErrorDetail ({message, reason}); pydantic body validation uses the default HTTPValidationError shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatePairErrorDetail"];
                };
            };
            /** @description Per-client rate limit for on-demand simulation */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reference mid unavailable or simulator not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
